language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  exclude:
	- php: 5.4
		env: PHPUNIT_VERSION='5.*@stable'
		env: PHPUNIT_VERSION='*@dev'
	- php: 5.5
		env: PHPUNIT_VERSION='5.*@stable'
		env: PHPUNIT_VERSION='*@dev'
	- php: 7.0
		env: PHPUNIT_VERSION='4.*@stable'
	- php: 7.0
		env: PHPUNIT_VERSION='3.7.*@stable'
  allow_failures:
    - env: PHPUNIT_VERSION='*@dev'
    - php: 7.0

env:
    - PHPUNIT_VERSION='3.7.*@stable'
    - PHPUNIT_VERSION='4.*@stable'
    - PHPUNIT_VERSION='5.*@stable'
    - PHPUNIT_VERSION='*@dev'

before_script:
    - composer self-update
    - composer require --no-update phpunit/phpunit=$PHPUNIT_VERSION
    - composer install --prefer-dist

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
