language: php

sudo: false

php:
    - "5.6"
    - hhvm
    - "5.5"
    - "5.4"
    - "5.3"

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly
    - env: PHPUNIT_VERSION='4.*@dev'

env:
    - PHPUNIT_VERSION='3.7.*'
    - PHPUNIT_VERSION='4.*@dev'
    - PHPUNIT_VERSION='4.*@stable'

before_script:
    - composer require --no-update phpunit/phpunit=$PHPUNIT_VERSION
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
